import assert from "node:assert/strict";
import fs from "node:fs";

const stockHtml = fs.readFileSync(new URL("../stock-pdc/index.html", import.meta.url), "utf8");
const decisionHtml = fs.readFileSync(new URL("../stock-pdc/decision/index.html", import.meta.url), "utf8");
const decisionJs = fs.readFileSync(new URL("../stock-pdc/decision/decision.js", import.meta.url), "utf8");
const stockFunction = fs.readFileSync(new URL("../functions/stock-pdc/[[path]].js", import.meta.url), "utf8");
const stockJs = fs.readFileSync(new URL("../stock-pdc/stock-pdc.js", import.meta.url), "utf8");

assert.ok(stockHtml.includes('href="/stock-pdc/decision/"'));
assert.ok(decisionHtml.includes('id="generateDecision"'));
assert.ok(decisionHtml.includes('id="decisionSteps"'));
assert.ok(decisionHtml.includes('id="modelGrid"'));
assert.ok(decisionHtml.includes('id="publishDecision"'));
assert.ok(decisionHtml.includes('id="copyDecisionPacket"'));
assert.ok(decisionHtml.includes('id="decisionModelSelect"'));
assert.ok(decisionHtml.includes('id="decisionModelNote"'));
assert.ok(decisionHtml.includes('id="dataContractTitle"'));
assert.ok(decisionHtml.includes('id="dataSnapshotId"'));
assert.ok(decisionHtml.includes('id="scoringContractTitle"'));
assert.ok(decisionHtml.includes("现在买入，未来 5 日会怎样？"));
assert.ok(decisionJs.includes('const DECISION_API_ENDPOINT = "/stock-pdc/decision/api"'));
assert.ok(decisionJs.includes("async function runDecisionFlow()"));
assert.ok(decisionJs.includes("async function runReviewers(stage)"));
assert.ok(decisionJs.includes('点击“继续生成”会从已保存的模型 PDC 继续'));
assert.ok(decisionJs.includes("async function publishDecision()"));
assert.ok(decisionJs.includes("async function loadModelProfiles()"));
assert.ok(decisionJs.includes("async function loadDataContract()"));
assert.ok(decisionJs.includes("function renderDataContract()"));
assert.ok(decisionJs.includes("async function restoreSavedRun()"));
assert.ok(decisionJs.includes('const RUN_STORAGE_KEY = "turnpo-stock-pdc-decision-run"'));
assert.ok(decisionJs.includes("modelProfileIds: state.selectedModelProfileIds"));
assert.ok(decisionJs.includes("第一轮独立盲评"));
assert.ok(decisionJs.includes("共识与风险闸门"));
assert.ok(decisionJs.includes("const decisionStages"));
assert.ok(decisionJs.includes("decision-process-stage"));
assert.ok(decisionJs.includes("function selectedModelProfiles()"));
assert.ok(decisionJs.includes("function renderModels()"));
assert.ok(decisionJs.includes("data-member-open"));
assert.ok(decisionJs.includes("function fullRunCopyText()"));
assert.ok(decisionJs.includes("function reviewCopyText("));
assert.ok(decisionJs.includes("function stepArtifact("));
assert.ok(decisionJs.includes("const PDC_DIMENSIONS"));
assert.ok(decisionJs.includes("function dimensionMarkup("));
assert.ok(decisionJs.includes("relativeStrength"));
assert.ok(decisionJs.includes("trendAcceleration"));
assert.ok(decisionJs.includes("entryTiming"));
assert.ok(decisionJs.includes("function forwardPredictionMarkup("));
assert.ok(stockFunction.includes('const DECISION_PATH = `${PAGE_PATH}/decision`;'));
assert.ok(stockFunction.includes("async function decisionApi(context)"));
assert.ok(stockFunction.includes("Save after every individual reviewer"));
assert.ok(stockFunction.includes("function normalizeProvenance(value)"));
assert.ok(stockFunction.includes("const FULL_PDC_ROLE"));
assert.ok(stockFunction.includes("function committeeMembers(run)"));
assert.ok(stockFunction.includes("facts: serializableCandidates(run.snapshot.candidates)"));
assert.ok(stockFunction.includes("const PDC_DIMENSIONS"));
assert.ok(stockFunction.includes('const PDC_SCORING_SYSTEM = "short-term-forward-upside-v2"'));
assert.ok(stockFunction.includes("function normalizeForwardPrediction"));
assert.ok(stockFunction.includes("function normalizeBackgroundChecks"));
assert.ok(stockFunction.includes("forwardOutcome"));
assert.ok(stockFunction.includes("function normalizeDimensionScores"));
assert.ok(stockFunction.includes("dimensionConsensus"));
assert.ok(stockFunction.includes("async function advanceCommitteeRun"));
assert.ok(stockFunction.includes('if (suffix === "models")'));
assert.ok(stockFunction.includes('const DEFAULT_STOCK_MODEL = "gpt-5.6-sol"'));
assert.ok(stockFunction.includes("OPENAI_STOCK_MODEL || DEFAULT_STOCK_MODEL"));
assert.ok(stockFunction.includes("ANTHROPIC_API_KEY || env.CLAUDE_API_KEY"));
assert.ok(stockFunction.includes('id: "claude_api_pdc"'));
assert.ok(stockFunction.includes("async function claudeReview"));
assert.ok(stockFunction.includes("GEMINI_API_KEY || env.GOOGLE_GEMINI_API_KEY"));
assert.ok(stockFunction.includes('id: "gemini_api_pdc"'));
assert.ok(stockFunction.includes("async function geminiReview"));
assert.ok(stockFunction.includes("DEEPSEEK_API_KEY || env.DEEPSEEK_PDC_API_KEY"));
assert.ok(stockFunction.includes('id: "deepseek_api_pdc"'));
assert.ok(stockFunction.includes("async function deepseekReview"));
assert.ok(stockFunction.includes("KIMI_API_KEY || env.MOONSHOT_API_KEY || env.KIMI_PDC_API_KEY"));
assert.ok(stockFunction.includes('id: "kimi_api_pdc"'));
assert.ok(stockFunction.includes("async function kimiReview"));
assert.ok(stockFunction.includes("stock-pdc:decision:day:"));
assert.ok(stockJs.includes('fetch("/stock-pdc/decision/api/history"'));
assert.ok(stockJs.includes("function renderPublishedDecisionHistory()"));

console.log("Stock PDC decision static checks passed");
