import assert from "node:assert/strict";
import fs from "node:fs";

const stockHtml = fs.readFileSync(new URL("../stock-pdc/index.html", import.meta.url), "utf8");
const decisionHtml = fs.readFileSync(new URL("../stock-pdc/decision/index.html", import.meta.url), "utf8");
const demoHtml = fs.readFileSync(new URL("../stock-pdc/decision-demo/index.html", import.meta.url), "utf8");
const portfolioHtml = fs.readFileSync(new URL("../stock-pdc/portfolio/index.html", import.meta.url), "utf8");
const portfolioJs = fs.readFileSync(new URL("../stock-pdc/portfolio/portfolio.js", import.meta.url), "utf8");
const decisionJs = fs.readFileSync(new URL("../stock-pdc/decision/decision.js", import.meta.url), "utf8");
const stockFunction = fs.readFileSync(new URL("../functions/stock-pdc/[[path]].js", import.meta.url), "utf8");
const stockJs = fs.readFileSync(new URL("../stock-pdc/stock-pdc.js", import.meta.url), "utf8");

assert.ok(stockHtml.includes('href="/stock-pdc/decision/"'));
assert.ok(decisionHtml.includes('id="generateDecision"'));
assert.ok(decisionHtml.includes('id="testDecision"'));
assert.ok(decisionHtml.includes('class="decision-workflow"'));
assert.ok(decisionHtml.includes('id="decisionWorkflow"'));
assert.ok(decisionHtml.includes('href="/stock-pdc/decision-demo/"'));
assert.ok(stockHtml.includes('href="/stock-pdc/portfolio/"'));
assert.ok(demoHtml.includes("Mini 决策"));
assert.ok(demoHtml.includes('id="testDecision"'));
assert.ok(demoHtml.includes('class="decision-workflow"'));
assert.ok(demoHtml.includes('id="decision-run-strip"') || demoHtml.includes('class="decision-run-strip"'));
assert.ok(demoHtml.includes('id="dataContractTitle"'));
assert.ok(demoHtml.includes('id="scoringContractTitle"'));
assert.ok(demoHtml.includes("现在买入，未来 5 日会怎样？"));
assert.ok(demoHtml.includes('id="decisionArchive"'));
assert.ok(demoHtml.includes('id="decisionResult"'));
assert.ok(portfolioHtml.includes("BUY TODAY"));
assert.ok(portfolioHtml.includes("HOLD"));
assert.ok(portfolioHtml.includes("SELL TODAY"));
assert.ok(portfolioHtml.includes('id="runNoonRecheck"'));
assert.ok(portfolioHtml.includes('id="entryForm"'));
assert.ok(portfolioHtml.includes('id="exitForm"'));
assert.ok(portfolioJs.includes('const PORTFOLIO_API = "/stock-pdc/portfolio/api"'));
assert.ok(portfolioJs.includes("11:30 最新可用价格"));
assert.ok(demoHtml.includes('href="/stock-pdc/decision/"'));
assert.ok(decisionHtml.includes('id="decisionSteps"'));
assert.ok(decisionHtml.includes('id="modelGrid"'));
assert.ok(decisionHtml.includes('id="publishDecision"'));
assert.ok(decisionHtml.includes('id="copyDecisionPacket"'));
assert.ok(decisionHtml.includes('data-copy-run'));
assert.ok(demoHtml.includes('data-copy-run'));
assert.ok(decisionHtml.includes('id="decisionModelSelect"'));
assert.ok(decisionHtml.includes('id="decisionModelNote"'));
assert.ok(decisionHtml.includes('id="dataContractTitle"'));
assert.ok(decisionHtml.includes('id="dataSnapshotId"'));
assert.ok(decisionHtml.includes('id="scoringContractTitle"'));
assert.ok(decisionHtml.includes("现在买入，未来 5 日会怎样？"));
assert.ok(decisionHtml.includes("本轮输出"));
assert.ok(demoHtml.includes("本轮输出"));
assert.ok(decisionJs.includes('const IS_DEMO_MODE = window.location.pathname.startsWith("/stock-pdc/decision-demo")'));
assert.ok(decisionJs.includes('"/stock-pdc/decision-demo/api"'));
assert.ok(decisionJs.includes("async function runDecisionFlow()"));
assert.ok(decisionJs.includes("async function runSmokeTest()"));
assert.ok(decisionJs.includes('api("/smoke-test"'));
assert.ok(decisionJs.includes("未读取股票数据、未做评分、未创建 Run"));
assert.ok(decisionJs.includes("async function runReviewers(stage)"));
assert.ok(decisionJs.includes("已返回的模型结论已保留"));
assert.ok(decisionJs.includes("async function publishDecision()"));
assert.ok(decisionJs.includes("async function loadModelProfiles()"));
assert.ok(decisionJs.includes("async function loadDataContract()"));
assert.ok(decisionJs.includes('fetch("/stock-pdc/hawkeye/latest.json"'));
assert.ok(decisionJs.includes("Hawkeye Radar is not ready"));
assert.ok(!decisionJs.includes('fetch("/stock-pdc/rank-flow.json"'));
assert.ok(!decisionJs.includes("body: JSON.stringify({ snapshot,"));
assert.ok(decisionJs.includes("function renderDataContract()"));
assert.ok(decisionJs.includes("async function restoreSavedRun()"));
assert.ok(decisionJs.includes('"turnpo-stock-pdc-decision-demo-run"'));
assert.ok(decisionJs.includes("modelProfileIds: state.selectedModelProfileIds"));
assert.ok(decisionJs.includes("第一轮独立盲评"));
assert.ok(decisionJs.includes("共识与风险闸门"));
assert.ok(decisionJs.includes("const WORKFLOW_STAGES"));
assert.ok(decisionJs.includes("Secretary 汇总"));
assert.ok(decisionJs.includes("function renderWorkflow"));
assert.ok(decisionJs.includes("function workflowMemberRecords"));
assert.ok(decisionJs.includes('const archive = $("#decisionArchive")'));
assert.ok(decisionJs.includes("function selectedModelProfiles()"));
assert.ok(decisionJs.includes("function renderModels()"));
assert.ok(decisionJs.includes("function verificationReceiptMarkup("));
assert.ok(decisionJs.includes("data-member-open"));
assert.ok(decisionJs.includes("function fullRunCopyText()"));
assert.ok(decisionJs.includes('document.querySelectorAll("[data-copy-run]"'));
assert.ok(decisionJs.includes("function reviewCopyText("));
assert.ok(decisionJs.includes("function stepArtifact("));
assert.ok(decisionJs.includes("const PDC_DIMENSIONS"));
assert.ok(decisionJs.includes("function dimensionMarkup("));
assert.ok(decisionJs.includes("relativeStrength"));
assert.ok(decisionJs.includes("trendAcceleration"));
assert.ok(decisionJs.includes("entryTiming"));
assert.ok(decisionJs.includes("function forwardPredictionMarkup("));
assert.ok(stockFunction.includes('const DECISION_PATH = `${PAGE_PATH}/decision`;'));
assert.ok(stockFunction.includes('const DEMO_DECISION_PATH = `${PAGE_PATH}/decision-demo`;'));
assert.ok(stockFunction.includes('const PORTFOLIO_PATH = `${PAGE_PATH}/portfolio`;'));
assert.ok(stockFunction.includes("async function decisionApi(context, mode = OFFICIAL_DECISION_MODE)"));
assert.ok(stockFunction.includes("async function smokeTestDecision(request, env, mode = OFFICIAL_DECISION_MODE)"));
assert.ok(stockFunction.includes("const SMOKE_TEST_PROMPT"));
assert.ok(stockFunction.includes("const SMOKE_TEST_TIMEOUT_MS = 5 * 60 * 1000"));
assert.ok(stockFunction.includes("const MAX_SMOKE_TESTS_PER_DAY = 60"));
assert.ok(stockFunction.includes('thinkingLevel: "low"'));
assert.ok(decisionJs.includes('path === "/smoke-test" ? 5 * 60 * 1000 : path.endsWith("/secretary")'));
assert.ok(decisionJs.includes("Promise.all(profiles.map(async (profile) =>"));
assert.ok(stockFunction.includes("Save after every individual reviewer"));
assert.ok(stockFunction.includes("function normalizeProvenance(value)"));
assert.ok(stockFunction.includes("function normalizeFacts(value)"));
assert.ok(stockFunction.includes("facts: candidate.facts"));
assert.ok(stockFunction.includes("async function serverHawkeyeSnapshot(request)"));
assert.ok(stockFunction.includes("The browser may not supply Hawkeye candidates"));
assert.ok(!stockFunction.includes("slice(0, MAX_CANDIDATES)"));
assert.ok(stockFunction.includes("const FULL_PDC_ROLE"));
assert.ok(stockFunction.includes("function committeeMembers(run)"));
assert.ok(stockFunction.includes("facts: serializableCandidates(run.snapshot.candidates)"));
assert.ok(stockFunction.includes("const PDC_DIMENSIONS"));
assert.ok(stockFunction.includes('const PDC_SCORING_SYSTEM = "short-term-forward-upside-v2"'));
assert.ok(stockFunction.includes("function normalizeForwardPrediction"));
assert.ok(stockFunction.includes("function normalizeBackgroundChecks"));
assert.ok(stockFunction.includes("forwardOutcome"));
assert.ok(stockFunction.includes("function publicModelVerification("));
assert.ok(stockFunction.includes("function normalizeDimensionScores"));
assert.ok(stockFunction.includes("dimensionConsensus"));
assert.ok(stockFunction.includes("async function advanceCommitteeRun"));
assert.ok(stockFunction.includes("async function secretaryReview"));
assert.ok(stockFunction.includes('id: "pdc_secretary"'));
assert.ok(stockFunction.includes("stage === \"secretary\""));
assert.ok(stockFunction.includes('if (suffix === "models")'));
assert.ok(stockFunction.includes('const DEFAULT_STOCK_MODEL = "gpt-5.6-sol"'));
assert.ok(stockFunction.includes('const DEFAULT_DEMO_STOCK_MODEL = "gpt-5.6-luna"'));
assert.ok(stockFunction.includes('const DEFAULT_CLAUDE_DEMO_STOCK_MODEL = "claude-haiku-4-5-20251001"'));
assert.ok(stockFunction.includes('const DEFAULT_GEMINI_DEMO_STOCK_MODEL = "gemini-3.5-flash-lite"'));
assert.ok(stockFunction.includes('const DEFAULT_DEEPSEEK_DEMO_STOCK_MODEL = "deepseek-v4-flash"'));
assert.ok(stockFunction.includes('const DEFAULT_KIMI_DEMO_STOCK_MODEL = "kimi-k2.6"'));
assert.ok(stockFunction.includes("Mini Demo runs are intentionally isolated"));
assert.ok(stockFunction.includes("const PORTFOLIO_DEFAULT_CONFIG"));
assert.ok(stockFunction.includes("async function portfolioApi(context)"));
assert.ok(stockFunction.includes("HARD_STOP"));
assert.ok(stockFunction.includes("PDC_RANK_EXIT"));
assert.ok(stockFunction.includes("PORTFOLIO_REPLACEMENT"));
assert.ok(stockFunction.includes("11:30_LATEST_AVAILABLE_PRICE"));
assert.ok(stockFunction.includes("OPENAI_STOCK_MODEL || DEFAULT_STOCK_MODEL"));
assert.ok(stockFunction.includes("ANTHROPIC_API_KEY || env.CLAUDE_API_KEY"));
assert.ok(stockFunction.includes('id: "claude_api_pdc"'));
assert.ok(stockFunction.includes("async function claudeReview"));
assert.ok(stockFunction.includes("GEMINI_API_KEY || env.GOOGLE_GEMINI_API_KEY"));
assert.ok(stockFunction.includes('id: "gemini_api_pdc"'));
assert.ok(stockFunction.includes("async function geminiReview"));
assert.ok(stockFunction.includes("responseJsonSchema: portableReviewSchema()"));
assert.ok(stockFunction.includes("DEEPSEEK_API_KEY || env.DEEPSEEK_PDC_API_KEY"));
assert.ok(stockFunction.includes('id: "deepseek_api_pdc"'));
assert.ok(stockFunction.includes("async function deepseekReview"));
assert.ok(stockFunction.includes("KIMI_API_KEY || env.MOONSHOT_API_KEY || env.KIMI_PDC_API_KEY"));
assert.ok(stockFunction.includes('id: "kimi_api_pdc"'));
assert.ok(stockFunction.includes("async function kimiReview"));
assert.ok(stockFunction.includes('const KIMI_CHAT_URL = "https://api.moonshot.cn/v1/chat/completions"'));
assert.ok(stockFunction.includes('return mode === DEMO_DECISION_MODE ? "stock-pdc:decision-demo" : "stock-pdc:decision";'));
assert.ok(stockJs.includes('fetch("/stock-pdc/decision/api/history"'));
assert.ok(stockJs.includes("function renderPublishedDecisionHistory()"));

console.log("Stock PDC decision static checks passed");
