import assert from "node:assert/strict";
import fs from "node:fs";

const stockHtml = fs.readFileSync(new URL("../stock-pdc/index.html", import.meta.url), "utf8");
const decisionHtml = fs.readFileSync(new URL("../stock-pdc/decision/index.html", import.meta.url), "utf8");
const decisionJs = fs.readFileSync(new URL("../stock-pdc/decision/decision.js", import.meta.url), "utf8");
const stockFunction = fs.readFileSync(new URL("../functions/stock-pdc/[[path]].js", import.meta.url), "utf8");
const stockJs = fs.readFileSync(new URL("../stock-pdc/stock-pdc.js", import.meta.url), "utf8");
const decisionCandidates = JSON.parse(fs.readFileSync(new URL("../stock-pdc/decision-candidates.json", import.meta.url), "utf8"));

assert.ok(stockHtml.includes('href="/stock-pdc/decision/"'));
assert.ok(decisionHtml.includes('id="generateDecision"'));
assert.ok(decisionHtml.includes('id="decisionSteps"'));
assert.ok(decisionHtml.includes('id="modelGrid"'));
assert.ok(decisionHtml.includes('id="publishDecision"'));
assert.ok(decisionHtml.includes('id="nextDecisionStep"'));
assert.ok(decisionHtml.includes('id="runAllDecision"'));
assert.ok(decisionHtml.includes('id="decisionReview"'));
assert.ok(decisionJs.includes('const DECISION_API_ENDPOINT = "/stock-pdc/decision/api"'));
assert.ok(decisionJs.includes("async function runDecisionFlow()"));
assert.ok(decisionJs.includes("async function publishDecision()"));
assert.ok(decisionJs.includes("DECISION_RUN_KEY"));
assert.ok(decisionJs.includes("restoreSavedRun"));
assert.ok(decisionJs.includes("nextStageForRun"));
assert.ok(decisionJs.includes("startStepByStep"));
assert.ok(decisionJs.includes("advanceNextStep"));
assert.ok(decisionJs.includes("renderReview"));
assert.ok(decisionJs.includes('fetch("/stock-pdc/decision-candidates.json"'));
assert.ok(decisionJs.includes("第一轮独立盲评"));
assert.ok(decisionJs.includes("市场与风险闸门"));
assert.ok(decisionJs.includes("GPT mini · PDC"));
assert.ok(stockFunction.includes('const DECISION_PATH = `${PAGE_PATH}/decision`;'));
assert.ok(stockFunction.includes("async function decisionApi(context)"));
assert.ok(stockFunction.includes("OPENAI_STOCK_MODEL || env.OPENAI_MODEL || DEFAULT_STOCK_MODEL"));
assert.ok(stockFunction.includes("stock-pdc:decision:day:"));
assert.ok(stockFunction.includes("const MAX_CANDIDATES = 500"));
assert.ok(stockFunction.includes("const MAX_RECOMMENDATIONS_PER_ROLE = 20"));
assert.ok(stockFunction.includes("MAX_MERGED_CANDIDATES"));
assert.ok(stockJs.includes('fetch("/stock-pdc/decision/api/history"'));
assert.ok(stockJs.includes("function renderPublishedDecisionHistory()"));
assert.ok(!decisionHtml.includes("30–40"));
assert.ok(!decisionHtml.includes("4 × Top 30"));
assert.equal(decisionCandidates.schemaVersion, "stock-pdc-decision-candidates-v1");
assert.equal(decisionCandidates.availability, "ACTIVE");
assert.ok(decisionCandidates.candidates.length >= 5);

console.log("Stock PDC decision static checks passed");
